PHP 8.2 support
ScrumWorks/property-reader pull request #8
Opened 2023-03-09 08:29 UTC by dada-amater

#### What's this PR do?
Podpora pro PHP 8.2 a cleanup

2023-03-09 08:29 UTC, dada-amater commented
Task linked: [AMA-5734 Upgrade na PHP 8.2 (backend)](https://app.clickup.com/t/2439381/AMA-5734)

2023-03-10 08:41 UTC, AdamLutka requested changes

2023-03-10 08:41 UTC, AdamLutka commented on .gitignore
> -composer.lock
Lock do klihoven nepatri.

2023-03-10 11:55 UTC, AdamLutka requested changes
Proc revert? Vyhod commit z vetve ne?

2023-03-10 12:14 UTC, dada-amater commented
> Proc revert? Vyhod commit z vetve ne?

Jo, nechtel jsem behem CR menit historii.

2023-03-10 12:17 UTC, AdamLutka approved these changes

2023-03-10 12:19 UTC, merged